# Generated by Django 2.2.1 on 2019-05-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0004_auto_20190524_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohoraextra',
            name='horas',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
