# Generated by Django 2.2.1 on 2019-06-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_auto_20190522_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='imagem',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
